version: '2'
services:
    web:
        build: .
        container_name: "web"
        restart: always
        environment:
            NODE_ENV: development
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: admin
        volumes:
          - ".:/app/"
        ports:
          - "3000:3000"
          - "8080:8080"
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        restart: always
        environment:
            MONGO_DATA_DIR: /data/db
            MONGO_LOG_DIR: /dev/null
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
        volumes:
          - "./data/db:/data/db"
        ports:
          - "27017:27017"
        command: mongod --smallfiles --logpath=/dev/null # --quiet
